######################################################################
# Automatically generated by qmake (3.0) su maalis 16 13:43:48 2014
######################################################################

QT          += gui widgets

TEMPLATE    = app
TARGET      = personmanager
INCLUDEPATH += .

# Input
HEADERS     += lecturer.h person.h student.h \
               gui.h

SOURCES     += lecturer.cpp main.cpp person.cpp student.cpp \
               gui.cpp

FORMS       += gui.ui
